repos:
  - repo: local
    hooks:
      - id: lint-patch
        name: Lint and Patch Python Files
        entry: python lint_patch.py
        language: system
        files: '\.py$'
        stages: [commit]
