name: Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Python tests
      run: |
        pytest tests/

    - name: Python Code Style Check
      run: |
        pip install flake8 black isort
        # Flake8 for style guide enforcement
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv
        # Black for code formatting
        black --check --diff --exclude=.venv .
        # isort for import sorting
        isort --check-only --diff --skip .venv .