name: Release

on:
  pull_request:
    branches: 
      - main
    types: [opened, synchronize]
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pr_version_and_changelog:
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/v')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          VERSION=${BRANCH_NAME#release/v}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Generate Changelog Preview
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Preview Release ${{ steps.extract_version.outputs.version }}
          tag: ${{ steps.extract_version.outputs.version }}
          body: |
            **Changelog Preview for ${{ steps.extract_version.outputs.version }}**
            
            ```bash
            git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" --no-merges  
            ```
          draft: true
          prerelease: true

      - name: Save Changelog Preview
        run: echo "${{ steps.changelog_preview.outputs.body }}" > changelog-preview.txt

      - name: Upload Changelog Artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog-preview
          path: changelog-preview.txt

  create_release:
    needs: pr_version_and_changelog
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Changelog Preview
        uses: actions/download-artifact@v4
        with:
          name: changelog-preview

      - name: Update CHANGELOG.md
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## ${{ steps.extract_version.outputs.version }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" --no-merges >> CHANGELOG.md

      - name: Commit CHANGELOG.md
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for ${{ steps.extract_version.outputs.version }}"

      - name: Create Tag
        run: |
          git tag -a v${{ steps.extract_version.outputs.version }} -m "Version ${{ steps.extract_version.outputs.version }}"
          git push origin v${{ steps.extract_version.outputs.version }}

      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ steps.extract_version.outputs.version }}
          tag: v${{ steps.extract_version.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
